package cn.ssmc.entity;

import java.util.Date;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.id
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.no
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.name
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.nickname
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.password
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.sex
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.birthday
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.address
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.path
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.id
     *
     * @return the value of t_admin.id
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.id
     *
     * @param id the value for t_admin.id
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.no
     *
     * @return the value of t_admin.no
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.no
     *
     * @param no the value for t_admin.no
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.name
     *
     * @return the value of t_admin.name
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.name
     *
     * @param name the value for t_admin.name
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.nickname
     *
     * @return the value of t_admin.nickname
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.nickname
     *
     * @param nickname the value for t_admin.nickname
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.password
     *
     * @return the value of t_admin.password
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.password
     *
     * @param password the value for t_admin.password
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.sex
     *
     * @return the value of t_admin.sex
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.sex
     *
     * @param sex the value for t_admin.sex
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.birthday
     *
     * @return the value of t_admin.birthday
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.birthday
     *
     * @param birthday the value for t_admin.birthday
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.address
     *
     * @return the value of t_admin.address
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.address
     *
     * @param address the value for t_admin.address
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.path
     *
     * @return the value of t_admin.path
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.path
     *
     * @param path the value for t_admin.path
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }
}