package cn.ssmc.entity;

public class ChooseCourse {
	
    private Integer id;
    private String no;
    
    private Course course;

    private College college;
    
    private Teacher teacher;
    
    private Terms terms;

    private ClassTime classTime;
    
    private Integer max;
    private Integer selected;
    private Integer flag;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chos.id
     *
     * @param id the value for t_chos.id
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chos.no
     *
     * @return the value of t_chos.no
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chos.no
     *
     * @param no the value for t_chos.no
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    public Integer getMax() {
        return max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chos.max
     *
     * @param max the value for t_chos.max
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setMax(Integer max) {
        this.max = max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chos.selected
     *
     * @return the value of t_chos.selected
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public Integer getSelected() {
        return selected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chos.selected
     *
     * @param selected the value for t_chos.selected
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setSelected(Integer selected) {
        this.selected = selected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chos.flag
     *
     * @return the value of t_chos.flag
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chos.flag
     *
     * @param flag the value for t_chos.flag
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

	public Course getCourse() {
		return course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public College getCollege() {
		return college;
	}

	public void setCollege(College college) {
		this.college = college;
	}

	public Teacher getTeacher() {
		return teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public Terms getTerms() {
		return terms;
	}

	public void setTerms(Terms terms) {
		this.terms = terms;
	}

	public ClassTime getClassTime() {
		return classTime;
	}

	public void setClassTime(ClassTime classTime) {
		this.classTime = classTime;
	}

	@Override
	public String toString() {
		return "ChooseCourse [id=" + id + ", no=" + no + ", course=" + course + ", max=" + max + ", selected="
				+ selected + ", flag=" + flag + "]";
	}
	
}