package cn.ssmc.entity;

public class ClassTime {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classtime.id
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classtime.no
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classtime.class_name
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classtime.time
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classtime.size
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private Integer size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classtime.flag
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classtime.id
     *
     * @return the value of t_classtime.id
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classtime.id
     *
     * @param id the value for t_classtime.id
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classtime.no
     *
     * @return the value of t_classtime.no
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classtime.no
     *
     * @param no the value for t_classtime.no
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classtime.class_name
     *
     * @return the value of t_classtime.class_name
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classtime.class_name
     *
     * @param className the value for t_classtime.class_name
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classtime.time
     *
     * @return the value of t_classtime.time
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classtime.time
     *
     * @param time the value for t_classtime.time
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classtime.size
     *
     * @return the value of t_classtime.size
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classtime.size
     *
     * @param size the value for t_classtime.size
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classtime.flag
     *
     * @return the value of t_classtime.flag
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classtime.flag
     *
     * @param flag the value for t_classtime.flag
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

	@Override
	public String toString() {
		return "ClassTime [id=" + id + ", no=" + no + ", className=" + className + ", time=" + time + ", size=" + size
				+ ", flag=" + flag + "]";
	}
    
}