package cn.ssmc.entity;

public class College {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_college.id
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_college.no
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_college.name
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_college.id
     *
     * @return the value of t_college.id
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_college.id
     *
     * @param id the value for t_college.id
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_college.no
     *
     * @return the value of t_college.no
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_college.no
     *
     * @param no the value for t_college.no
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_college.name
     *
     * @return the value of t_college.name
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_college.name
     *
     * @param name the value for t_college.name
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

	@Override
	public String toString() {
		return "College [id=" + id + ", no=" + no + ", name=" + name + "]";
	}
    
}