package cn.ssmc.entity;

public class Course {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_course.id
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_course.no
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */
	private String no;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_course.name
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_course.hour
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */
	private Integer hour;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_course.credit
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */
	private Double credit;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_course.college_id
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */

	private College college;

	public College getCollege() {
		return college;
	}

	public void setCollege(College college) {
		this.college = college;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_course.id
	 *
	 * @return the value of t_course.id
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_course.id
	 *
	 * @param id
	 *            the value for t_course.id
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_course.no
	 *
	 * @return the value of t_course.no
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */
	public String getNo() {
		return no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_course.no
	 *
	 * @param no
	 *            the value for t_course.no
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */
	public void setNo(String no) {
		this.no = no == null ? null : no.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_course.name
	 *
	 * @return the value of t_course.name
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_course.name
	 *
	 * @param name
	 *            the value for t_course.name
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_course.hour
	 *
	 * @return the value of t_course.hour
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */
	public Integer getHour() {
		return hour;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_course.hour
	 *
	 * @param hour
	 *            the value for t_course.hour
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */
	public void setHour(Integer hour) {
		this.hour = hour;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_course.credit
	 *
	 * @return the value of t_course.credit
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */
	public Double getCredit() {
		return credit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_course.credit
	 *
	 * @param credit
	 *            the value for t_course.credit
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */
	public void setCredit(Double credit) {
		this.credit = credit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_course.college_id
	 *
	 * @return the value of t_course.college_id
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_course.college_id
	 *
	 * @param collegeId
	 *            the value for t_course.college_id
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */

	@Override
	public String toString() {
		return "Course [id=" + id + ", no=" + no + ", name=" + name + ", hour=" + hour + ", credit=" + credit;
	}

}