package cn.ssmc.entity;

public class Major {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major.id
     *
     * @mbg.generated Mon Aug 21 09:35:02 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major.no
     *
     * @mbg.generated Mon Aug 21 09:35:02 CST 2017
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major.name
     *
     * @mbg.generated Mon Aug 21 09:35:02 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major.college_id
     *
     * @mbg.generated Mon Aug 21 09:35:02 CST 2017
     */
    private Integer collegeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major.id
     *
     * @return the value of t_major.id
     *
     * @mbg.generated Mon Aug 21 09:35:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major.id
     *
     * @param id the value for t_major.id
     *
     * @mbg.generated Mon Aug 21 09:35:02 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major.no
     *
     * @return the value of t_major.no
     *
     * @mbg.generated Mon Aug 21 09:35:02 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major.no
     *
     * @param no the value for t_major.no
     *
     * @mbg.generated Mon Aug 21 09:35:02 CST 2017
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major.name
     *
     * @return the value of t_major.name
     *
     * @mbg.generated Mon Aug 21 09:35:02 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major.name
     *
     * @param name the value for t_major.name
     *
     * @mbg.generated Mon Aug 21 09:35:02 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major.college_id
     *
     * @return the value of t_major.college_id
     *
     * @mbg.generated Mon Aug 21 09:35:02 CST 2017
     */
    public Integer getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major.college_id
     *
     * @param collegeId the value for t_major.college_id
     *
     * @mbg.generated Mon Aug 21 09:35:02 CST 2017
     */
    public void setCollegeId(Integer collegeId) {
        this.collegeId = collegeId;
    }
}