package cn.ssmc.entity;

import java.util.Date;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.id
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.no
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.name
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.nickname
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.password
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.sex
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.birthday
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.address
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.path
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.credit
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    private Double credit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.e_year
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    private String eYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.s_year
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    private Integer sYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.college_id
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    private College college;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.major_id
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    private Major major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.major_name
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */

    public College getCollege() {
		return college;
	}

	public void setCollege(College college) {
		this.college = college;
	}

	public Major getMajor() {
		return major;
	}

	public void setMajor(Major major) {
		this.major = major;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.id
     *
     * @return the value of t_student.id
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.id
     *
     * @param id the value for t_student.id
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.no
     *
     * @return the value of t_student.no
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.no
     *
     * @param no the value for t_student.no
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.name
     *
     * @return the value of t_student.name
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.name
     *
     * @param name the value for t_student.name
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.nickname
     *
     * @return the value of t_student.nickname
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.nickname
     *
     * @param nickname the value for t_student.nickname
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.password
     *
     * @return the value of t_student.password
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.password
     *
     * @param password the value for t_student.password
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.sex
     *
     * @return the value of t_student.sex
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.sex
     *
     * @param sex the value for t_student.sex
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.birthday
     *
     * @return the value of t_student.birthday
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.birthday
     *
     * @param birthday the value for t_student.birthday
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.address
     *
     * @return the value of t_student.address
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.address
     *
     * @param address the value for t_student.address
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.path
     *
     * @return the value of t_student.path
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.path
     *
     * @param path the value for t_student.path
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.credit
     *
     * @return the value of t_student.credit
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public Double getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.credit
     *
     * @param credit the value for t_student.credit
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public void setCredit(Double credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.e_year
     *
     * @return the value of t_student.e_year
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public String geteYear() {
        return eYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.e_year
     *
     * @param eYear the value for t_student.e_year
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public void seteYear(String eYear) {
        this.eYear = eYear == null ? null : eYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.s_year
     *
     * @return the value of t_student.s_year
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public Integer getsYear() {
        return sYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.s_year
     *
     * @param sYear the value for t_student.s_year
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public void setsYear(Integer sYear) {
        this.sYear = sYear;
    }

	@Override
	public String toString() {
		return "Student [id=" + id + ", no=" + no + ", name=" + name + ", nickname=" + nickname + ", password="
				+ password + ", sex=" + sex + ", birthday=" + birthday + ", address=" + address + ", path=" + path
				+ ", credit=" + credit + ", eYear=" + eYear + ", sYear=" + sYear + "]";
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.college_id
     *
     * @return the value of t_student.college_id
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
   
}