package cn.ssmc.entity;

public class StudentChos {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_chos.id
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_chos.chos_id
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    private ChooseCourse chooseCourse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_chos.student_id
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    private Student student;

    
    
    private Integer score=0;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_chos.id
     *
     * @return the value of student_chos.id
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_chos.id
     *
     * @param id the value for student_chos.id
     *
     * @mbg.generated Mon Aug 21 10:16:56 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

   
    
    public Integer getScore() {
        return score;
    }

   
    public ChooseCourse getChooseCourse() {
		return chooseCourse;
	}

	public void setChooseCourse(ChooseCourse chooseCourse) {
		this.chooseCourse = chooseCourse;
	}

	public Student getStudent() {
		return student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public void setScore(Integer score) {
        this.score = score;
    }

	@Override
	public String toString() {
		return "StudentChos [id=" + id + ", score=" + score + "]";
	}
	
}