package cn.ssmc.entity;

import java.util.Date;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.id
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.no
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.name
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.nickname
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.password
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.sex
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.birthday
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.address
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.path
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.college_id
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    private College college;

    
    public College getCollege() {
		return college;
	}

	public void setCollege(College college) {
		this.college = college;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.id
     *
     * @return the value of t_teacher.id
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.id
     *
     * @param id the value for t_teacher.id
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.no
     *
     * @return the value of t_teacher.no
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.no
     *
     * @param no the value for t_teacher.no
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.name
     *
     * @return the value of t_teacher.name
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.name
     *
     * @param name the value for t_teacher.name
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.nickname
     *
     * @return the value of t_teacher.nickname
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.nickname
     *
     * @param nickname the value for t_teacher.nickname
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.password
     *
     * @return the value of t_teacher.password
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.password
     *
     * @param password the value for t_teacher.password
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.sex
     *
     * @return the value of t_teacher.sex
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.sex
     *
     * @param sex the value for t_teacher.sex
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.birthday
     *
     * @return the value of t_teacher.birthday
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.birthday
     *
     * @param birthday the value for t_teacher.birthday
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.address
     *
     * @return the value of t_teacher.address
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.address
     *
     * @param address the value for t_teacher.address
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.path
     *
     * @return the value of t_teacher.path
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.path
     *
     * @param path the value for t_teacher.path
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

	@Override
	public String toString() {
		return "Teacher [id=" + id + ", no=" + no + ", name=" + name + ", nickname=" + nickname + ", password="
				+ password + ", sex=" + sex + ", birthday=" + birthday + ", address=" + address + ", path=" + path
				+ "]";
	}

}