package cn.ssmc.dao;

import java.util.List;

import cn.ssmc.entity.ClassTime;

public interface ClassTimeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classtime
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classtime
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    int insert(ClassTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classtime
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    int insertSelective(ClassTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classtime
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    ClassTime selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classtime
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    int updateByPrimaryKeySelective(ClassTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classtime
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    int updateByPrimaryKey(ClassTime record);
    
    List<ClassTime> selectClassBySize(int classSize);
    
}