package cn.ssmc.dao;

import cn.ssmc.entity.Major;

public interface MajorDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_major
     *
     * @mbg.generated Mon Aug 21 09:35:02 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_major
     *
     * @mbg.generated Mon Aug 21 09:35:02 CST 2017
     */
    int insert(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_major
     *
     * @mbg.generated Mon Aug 21 09:35:03 CST 2017
     */
    int insertSelective(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_major
     *
     * @mbg.generated Mon Aug 21 09:35:03 CST 2017
     */
    Major selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_major
     *
     * @mbg.generated Mon Aug 21 09:35:03 CST 2017
     */
    int updateByPrimaryKeySelective(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_major
     *
     * @mbg.generated Mon Aug 21 09:35:03 CST 2017
     */
    int updateByPrimaryKey(Major record);
}