package cn.ssmc.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.ssmc.entity.ChooseCourse;
import cn.ssmc.entity.Course;
import cn.ssmc.entity.StudentChos;

public interface StudentChosDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_chos
     *
     * @mbg.generated Mon Aug 21 10:15:50 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_chos
     *
     * @mbg.generated Mon Aug 21 10:15:50 CST 2017
     */
    int insert(StudentChos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_chos
     *
     * @mbg.generated Mon Aug 21 10:15:50 CST 2017
     */
    int insertSelective(StudentChos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_chos
     *
     * @mbg.generated Mon Aug 21 10:15:50 CST 2017
     */
    StudentChos selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_chos
     *
     * @mbg.generated Mon Aug 21 10:15:50 CST 2017
     */
    int updateByPrimaryKeySelective(StudentChos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_chos
     *
     * @mbg.generated Mon Aug 21 10:15:50 CST 2017
     */
    int updateByPrimaryKey(StudentChos record);
    
    //传学生的id 看学生已经选了哪些课 
    //学生的idSESSION里面去，termflag 当前学期传2 ， 
    List<StudentChos> selectWithChooseStudView(@Param("studId")Integer studId,@Param("termFlag")Integer termFlag);
    
    //传选课的ID 查看有哪些学生选了该选课
    //传选课的学期 2-当前学期哪些学生选了该选课
    //传选课的学期1- 上学期学生的成绩
    List<StudentChos> selectWithChooseView (StudentChos studentChos);
    
    StudentChos isExist(@Param("ccID") int ccID, @Param("stdID") int stdID);
    
    int selectStudNum(int studId);

    StudentChos selectGetChooseByKey(int scID);
    
    StudentChos selectByKeyScore(int scID);
    
    List<ChooseCourse> selectCname(int teacherID);
}