package cn.ssmc.dao;

import java.util.List;

import cn.ssmc.entity.Teacher;

public interface TeacherDao {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_teacher
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_teacher
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */
	int insert(Teacher record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_teacher
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */
	int insertSelective(Teacher record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_teacher
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */
	Teacher selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_teacher
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */
	int updateByPrimaryKeySelective(Teacher record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_teacher
	 *
	 * @mbg.generated Sun Aug 20 13:05:37 CST 2017
	 */
	int updateByPrimaryKey(Teacher record);

	List<Teacher> selectTeacherByCollege(Integer college_id);

	// 老师登陆
	Teacher loginTeacher(Teacher record);
}