package cn.ssmc.dao;

import cn.ssmc.entity.Terms;

public interface TermsDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terms
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terms
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    int insert(Terms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terms
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    int insertSelective(Terms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terms
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    Terms selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terms
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    int updateByPrimaryKeySelective(Terms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terms
     *
     * @mbg.generated Sun Aug 20 13:05:37 CST 2017
     */
    int updateByPrimaryKey(Terms record);
    
    Terms selectNow();
    Terms selectBefore1();
}